### ISSUE TITLE
Nail the namespacing both here and for the appfail overlay

### ISSUE THREAD

**Issue by taitems** [skroonenburg/Appfail-JavaScript#13]
We have to get the two working in unison, ideally in any order as well. Include the overlay before **or** after the reporting module.

Current namespacing has a clunky `if`, this is cleaner:

`window.myApp = window.myApp || {};`

**Comment by taitems** [comment]
Namespacing in my fork is cleaned up, will need to be done separately in the overlay branch when you get time Sam.

**Comment by skroonenburg** [comment]
Done in overlay now. They both use the appfail root namespace. appfail.overlay and appfail.reporting.
Cheers!
