### ISSUE TITLE
Send Up Flattened Navigator Object (or individual props)

### ISSUE THREAD

**Issue by taitems** [skroonenburg/Appfail-JavaScript#2]
Sending up a flattened version of the `navigator` object will expose a host of useful properties depending on browser support. From there you can do some awesome filtering. For instance:

The `navigator.onLine` property will tell you if the error occured when the user was online or offline, perhaps they were attempting to access a resource while offline - so you can easily disregard or filter this error out.

Showing `navigator.standalone` is useful for determining if the web app is being run as a home screen app on a device etc.

We need to decide if we're sending this properties up individually, or if sending the whole `navigator` object up from the very beginning means we can retroactively add new filtering options because we have **always** collected the data.

**Comment by taitems** [comment]
@sbarski also said maybe this is a configuration option, so "ignoreOffline:true" means these errors are never sent to the server?

**Comment by skroonenburg** [comment]
Not done.... wanted to have a defined API... responding to a dynamic navigator is hard and scary :-)
