### ISSUE TITLE
Expose a beforesend method to parse POST values

### ISSUE THREAD

**Issue by taitems** [skroonenburg/Appfail-JavaScript#5]
As discussed, we should expose an `onbeforesend` event or something similar, so developers can parse the POST values and remove sensitive information like credit card numbers.

**Comment by skroonenburg** [comment]
Yes, please!

**Comment by taitems** [comment]
This is already in, but untested.

I did it before the error is pushed to the array, because you want to be able to parse it before it is stored to anything (eg: `localStorage`) because of the security implications.

**Comment by taitems** [comment]
Implemented in latest commit. Function is bound to `onBeforeStore`.
