### ISSUE TITLE
Allow for both query string and JSON object parameters

### ISSUE THREAD

**Issue by taitems** [skroonenburg/Appfail-JavaScript#6]
We need to allow for developers to set properties (such as `slug`) in the query string **as well as** allowing an object to be passed to the reporting module as parameters.

For example:

```
appfail.setup({
   slug: "h19f81398fh13f",
   queueInterval: 60000
});
```

**Comment by skroonenburg** [comment]
That'd be great... What about a generic method that grabs query string name/value pairs and sets a value using that name on the default settings object?

**Comment by taitems** [comment]
If I understand correctly I think that's already in, but also untested.

**Comment by taitems** [comment]
Established a proper syntax. Was mostly implemented before but now there are demo pages.
